--GET THE STUDENT BY THE NAME
SELECT SPR_FNM1, SPR_SURN FROM INS_SPR WHERE SPR_CODE=?

--GET THE
 SELECT CAM_SMO.MOD_CODE, MOD_NAME
 FROM CAM_SMO
 JOIN INS_MOD ON (CAM_SMO.MOD_CODE=INS_MOD.MOD_CODE)
 WHERE SPR_CODE='50200036' AND AYR_CODE='2016/7' AND PSL_CODE='TR1';
